os:
  - Ubuntu
shallow_clone: true
install:
- sudo apt update
- sudo apt install ocl-icd-opencl-dev
platform:
  - x64
configuration:
  - Release
environment:
  matrix:
   - SETARCH: i686
   - SETARCH: x86_64
matrix:
  exclude:
    - platform: Ubuntu
      SETARCH: x86_64
    - platform: x64
      SETARCH: i686
before_build:
  # Setup environment:
  - ps: $env:TOP = $env:APPVEYOR_BUILD_FOLDER
  - ps: $env:TOP
  - echo %TOP%
  # Generate the CTS solution file:
  - cmake -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=./bin
          -DOPENCL_LIBRARIES="OpenCL"
          -H. -Bbuild_win -A%PLATFORM%
          -DD3D10_IS_SUPPORTED=ON -DD3D11_IS_SUPPORTED=ON -DARCH=%SETARCH%
build:
  project: build_win\CLConform.sln
  parallel: true
  verbosity: normal